services:
    _defaults:
        autoconfigure: true

    Revierstil\DaytimeBundle\Repository\CategoryRepository:
        arguments:
            - '@doctrine'

    Revierstil\DaytimeBundle\Repository\TextRepository:
        arguments:
            - '@doctrine'
